import type {LayerSpecification} from 'maplibre-gl';

export const poi: LayerSpecification[] = [
  {
    id: 'poi-amenity',
    type: 'symbol',
    'source-layer': 'pois',
    filter: ['to-boolean', ['get', 'amenity']],
    source: 'versatiles-shortbread',
    minzoom: 13,
    layout: {
      'icon-size': 0.7,
      'text-field': '{name_en}',
      'icon-image': [
        'match',
        ['get', 'amenity'],
        'arts_centre',
        'versatiles:icon-art_gallery',
        'atm',
        'versatiles:icon-atm',
        'bank',
        'versatiles:icon-bank',
        'bar',
        'versatiles:icon-bar',
        'bench',
        'versatiles:icon-bench',
        'bicycle_rental',
        'versatiles:icon-bicycle_share',
        'biergarten',
        'versatiles:icon-beergarden',
        'cafe',
        'versatiles:icon-cafe',
        'car_rental',
        'versatiles:icon-car_rental',
        'car_sharing',
        'versatiles:icon-car_rental',
        'car_wash',
        'versatiles:icon-car_wash',
        'cinema',
        'versatiles:icon-cinema',
        'college',
        'versatiles:icon-college',
        'community_centre',
        'versatiles:icon-community',
        'dentist',
        'versatiles:icon-dentist',
        'doctors',
        'versatiles:icon-doctor',
        'dog_park',
        'versatiles:icon-dog_park',
        'drinking_water',
        'versatiles:icon-drinking_water',
        'embassy',
        'versatiles:icon-embassy',
        'fast_food',
        'versatiles:icon-fast_food',
        'fire_station',
        'versatiles:icon-fire_station',
        'fountain',
        'versatiles:icon-fountain',
        'grave_yard',
        'versatiles:icon-cemetery',
        'hospital',
        'versatiles:icon-hospital',
        'hunting_stand',
        'versatiles:icon-huntingstand',
        'library',
        'versatiles:icon-library',
        'marketplace',
        'versatiles:icon-marketplace',
        'nightclub',
        'versatiles:icon-nightclub',
        'nursing_home',
        'versatiles:icon-nursinghome',
        'pharmacy',
        'versatiles:icon-pharmacy',
        'place_of_worship',
        'versatiles:icon-place_of_worship',
        'playground',
        'versatiles:icon-playground',
        'police',
        'versatiles:icon-police',
        'post_box',
        'versatiles:icon-postbox',
        'post_office',
        'versatiles:icon-post',
        'prison',
        'versatiles:icon-prison',
        'pub',
        'versatiles:icon-beer',
        'recycling',
        'versatiles:icon-recycling',
        'restaurant',
        'versatiles:icon-restaurant',
        'school',
        'versatiles:icon-school',
        'shelter',
        'versatiles:icon-shelter',
        'telephone',
        'versatiles:icon-telephone',
        'theatre',
        'versatiles:icon-theatre',
        'toilets',
        'versatiles:icon-toilet',
        'townhall',
        'versatiles:icon-town_hall',
        'vending_machine',
        'versatiles:icon-vendingmachine',
        'veterinary',
        'versatiles:icon-veterinary',
        'waste_basket',
        'versatiles:icon-waste_basket',
        'unknown',
      ],
      'symbol-placement': 'point',
      'icon-optional': true,
      'text-font': ['noto_sans_regular'],
    },
    paint: {
      'icon-color': '#555555',
      'text-color': '#555555',
      'text-translate': [0, -20],
    },
  },
];
